name: Deployment

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Update JITpack repo
      run: |
        cd ../
        cp -r ./Genshindustry ./GenshindustryJitpack
        cd MindustryJitpack
        git clone --depth 1 https://github.com/WilloIzCitron/GenshindustryJitpack.git
        rm -rf .git
        cp -r ./GenshindustryJitpack/.git ./.git
        rm -rf GenshindustryJitpack
        rm -rf .github
        rm README.md
        git add .
        git commit --allow-empty -m "${GITHUB_SHA}"
        git push https://WilloIzCitron:${{ secrets.API_TOKEN_GITHUB }}@github.com/WilloIzCitron/GenshindustryJitpack
        git tag ${RELEASE_VERSION}
        git push https://WilloIzCitron:${{ secrets.API_TOKEN_GITHUB }}@github.com/WilloIzCitron/GenshindustryJitpack
        cd ../Genshindustry
    - name: Create artifacts
      run: |
        ./gradlew desktop:dist server:dist core:mergedJavadoc -Pbuildversion=${RELEASE_VERSION:1}
    - name: Upload client artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: desktop/build/libs/Mindustry.jar
        tag: ${{ github.ref }}
    - name: Upload server artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: server/build/libs/server-release.jar
        tag: ${{ github.ref }}

